export const actionTypes = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_RESPONSE: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
};

